---
- iptables:
    chain: INPUT
    policy: DROP

- iptables:
    chain: OUTPUT
    policy: DROP

- iptables:
   chain: FORWARD
   policy: DROP

- ufw: 
    rule: allow
    port: "{{ item }}"
    proto: tcp
    with_items:
      - 21
      - 22
      - 53
      - 123

- ufw:    
    rule: allow
    port: 53
    proto: udp
    


