---
- iptables:
    chain: INPUT
    policy: DROP

- iptables:
    chain: OUTPUT
    policy: DROP

-iptables:
   chain: FORWARD
   policy: DROP

- iptables_raw:
    name: allow tcp 21 22 53 123
    rules: '-A INPUT -p tcp --match multiport --dports 21,22,53,123 -j ACCEPT'

-  iptables_raw: 
     name: allow udp 53 
     rules: '-A INPUT -p udp --dport 53 -j ACCEPT'


