---
- name: make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Add sudoers users to wheel group
  user: name=manager groups=wheel append=yes state=present createhome=yes

- user:
    name: manager
    groups: wheel
    password: ilovetoeatkfc
    append: yes
 
- name: Placing key
  authorized_key:
    user=manager
    key="{{ lookup('file', '/home/student/Ansible/roles/common/files/id_rsa.pub') }}"

- name: Install mtr
  package:
    name: mtr
    state: latest

- name: install tcpdump
  package:
    name: tcpdump
    state: latest

- name: install nano
  package:
    name: nano
    state: latest

- name: set dns
  panos_mgtconfig:
    ip_address: "10.0.5.100"
    password: "electric dancy pants"
    dns_server_primary: "10.0.5.1"
    dns_server_secondary: "209.244.0.3"  
