---
- hosts: servers
  remote_user: root
  become: yes
  vars:
    ansible_ssh_user: root
    ansible_ssh_pass: electric dancy pants
  roles:
    -role: user_create
    -role: install_packages
    
  
